name: unlockGNN
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - cloudpickle
  - coverage
  - numpy
  - pip
  - pydocstyle
  - pytest
  - python=3.8
  - scipy=1.4.1
  - sphinx
  - sphinx_rtd_theme
  - pip:
      - bumpversion
      - coveralls
      - megnet
      - tensorflow-probability
      - twine
