name: unlockGNN
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - cloudpickle
  - coverage
  - numpy=1.19.*
  - pandas
  - pip
  - pydocstyle
  - pytest
  - python=3.8
  - sphinx
  - sphinx_rtd_theme
  - pip:
      - bumpversion
      - coveralls
      - pymatgen==2020.0.4
      - megnet
      - tensorflow-probability
      - twine
