name: unlockGNN
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - coverage
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyarrow
  - pydocstyle
  - pymatgen
  - pytest
  - pytest-cov
  - pytest-mock
  - python=3.8
  - scipy=1.4.1
  - seaborn
  - sphinx
  - sphinx_rtd_theme
  - pip:
      - matminer
      - megnet
      - git+https://github.com/WMD-group/SMACT.git
      - tensorflow-probability
      - tqdm
