name: unlockGNN
channels:
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyarrow
  - python=3.8
  - seaborn
  - pip:
      - matminer
      - megnet
      - pymatgen
      - git+https://github.com/WMD-group/SMACT.git
      - tensorflow-probability
      - tqdm
