name: unlockGNN
channels:
  - defaults
dependencies:
  - cloudpickle
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyarrow
  - python=3.8
  - scipy=1.4.1
  - seaborn
  - pip:
      - matminer
      - megnet
      - pymatgen==2020.4.29
      - git+https://github.com/WMD-group/SMACT.git
      - tensorflow==2.3.0
      - tensorflow-probability==0.11.0
      - tqdm
      - absl-py
      - google-api-python-client
      - wrapt
      - opt_einsum
      - astunparse
      - termcolor
