name: unlockGNN
channels:
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyarrow
  - python=3.8
  - seaborn
  - pip:
      - matminer
      - megnet
      - mlflow
      - pymatgen
      - smact
      - tensorflow-gpu
      - tensorflow-probability
      - tqdm
